# Generated by Django 4.2.18 on 2025-01-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Y2m8zaMQ2nQJxz8knW1yAvXj8IOLj6G6', editable=False, max_length=32, unique=True),
        ),
    ]
